const GAMETYPES = {
  EIGHT_QUEENS: 1,
  SHORTEST_PATH: 2,
  PREDICT_VAL_INDEX: 3,
  REMEMBER_VAL_INDEX: 4,
  TIC_TAC_TOE: 5,
};

const ANSWERSTATUS = {
  PENDING: 1,
  CORRECT: 2,
  INCORRECT: 3,
};

module.exports = { ANSWERSTATUS, GAMETYPES };
